### ISSUE TITLE
Yaml with a key called "on" parsed as True

### ISSUE THREAD

**Issue by Puneeth-n** [yaml/pyyaml#744] opened 2023-08-22 17:59 UTC
Hi, I am rather facing a weird issue with pyyaml library where a yaml string is not being parsed properly. the `on` key is parsed as boolean `True`. Any idea what is happening?

PyYAML==6.0 also tried the latest 5.x release

```bash
>>> import yaml
>>> yaml.full_load('on: {}')
{True: {}}
```

**Comment by nitzmahone** [comment] 2023-08-22 18:24
Duplicate of many issues, eg, https://github.com/yaml/pyyaml/issues/613 - by design until PyYAML properly supports YAML 1.2 behavior.

**Closed by nitzmahone** 2023-08-22 18:24 UTC

**Comment by nitzmahone** [comment] 2023-08-22 18:26
(see also https://github.com/yaml/pyyaml/issues/376#issuecomment-576821252 for a workaround)

**Comment by Puneeth-n** [comment] 2023-08-22 19:40
Thanks for the info. I changed the loader to baseloader and it did the trick.

**Comment by SashaSemenishchev** [comment] 2023-10-23 13:36
on = true
off = false
