### ISSUE TITLE
pyyaml should disable duplicate keys

### ISSUE THREAD

**Issue by zsfbct** [yaml/pyyaml#701] opened 2023-02-21 20:00 UTC
The YAML spec disables duplicate keys. When there exist duplicate keys, pyyaml doesn't catch it as an error but simply override.

For reference: https://stackoverflow.com/questions/53920358/pyyaml-loading-yaml-1-1-with-duplicate-keys

It should check keys uniqueness with similar logic to the code below in `constructor.py`
```
        if key in mapping:
             warnings.warn(somewarning)
        else:
            mapping[key] = value
```

**Comment by perlpunk** [comment] 2023-02-21 20:24
duplicate of #165 
Especially see my comment https://github.com/yaml/pyyaml/issues/165#issuecomment-525047100
So fixing it is not that trivial, but PRs that keep existing merge key behaviour are welcome.

**Closed** 2023-02-21 20:24 UTC
