### ISSUE TITLE
 HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl

### ISSUE THREAD

**Issue by Djston3** [yaml/pyyaml#204] opened 2018-07-13 10:56 UTC
I am getting errors try to pip3 install PyYAML,
the error message is

  HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
  Could not install requirement PyYAML from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff because of error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl
Could not install requirement PyYAML from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff because of HTTP error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl for URL https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)

so I checked the https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl, it returns PyYAML-4.1-cp35-cp35m-linux_armv7l.whl was not found on this server.
it seems like the file has been removed

**Comment by Djston3** [comment] 2018-07-13 11:04
fixed with manual install with the setup.py script, so if others have problem with pip3 install PyYAML.
please download this project and install with:
sudo python3 setup.py install

**Comment by NyanKiyoshi** [comment] 2018-07-13 11:33
Duplicate of #203

**Comment by ingydotnet** [comment] 2018-07-14 16:50
The latest PyYAML is 3.13. 4.1 was attempted and removed (before 3.13 was released). 4.2 will (very likely) be the next release.

**Closed by ingydotnet** 2018-07-14 16:50 UTC
