### ISSUE TITLE
[cython] AttributeError: type object '_yaml.Mark' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by seanyen** [yaml/pyyaml#423] opened 2020-07-31 22:26 UTC
This environment is not a typical one.

So I have a program which is using Python\C API to embed Python execution in a C\C++ native program. And one activity is to use "PyImport_ImportModule" to import a Python module for later use in C\C++ space. And for the python module to include, it depends on `PyYaml`. As it is importing, it fails at this call stack:
```
Traceback (most recent call last):
  File "C:\opt\ros\melodic\x64\lib\site-packages\sensor_msgs\msg\__init__.py", line 1, in <module>
    from ._BatteryState import *
  File "C:\opt\ros\melodic\x64\lib\site-packages\sensor_msgs\msg\_BatteryState.py", line 5, in <module>
    import genpy
  File "C:\opt\ros\melodic\x64\lib\site-packages\genpy\__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "C:\opt\ros\melodic\x64\lib\site-packages\genpy\message.py", line 47, in <module>
    import yaml
  File "C:\opt\python27amd64\lib\site-packages\yaml\__init__.py", line 14, in <module>
    from cyaml import *
  File "C:\opt\python27amd64\lib\site-packages\yaml\cyaml.py", line 5, in <module>
    from _yaml import CParser, CEmitter
  File "ext\_yaml.pyx", line 64, in init _yaml
AttributeError: type object '_yaml.Mark' has no attribute '__reduce_cython__'
```

By online searching for `AttributeError: type object 'xxx' has no attribute '__reduce_cython__'`, I saw many similar discussions and issues reported:
https://github.com/cython/cython/issues/1953
https://github.com/pynbody/pynbody/issues/503

If I understand it correctly, the actual cause is on `cython` side and the wheel built with the faulting version of `cython` will exhibit this behavior in the embedded environment.

For `PyYaml`, I confirmed this is a regression since `3.13` (yup, the problem existed for a while) and the last known good version for this problem is `3.12`.

I would suggest to pin a LKG version of `cython` as building the wheel for the next release.

**Comment by nitzmahone** [comment] 2020-07-31 22:53
Unfortunately that's not really an option- going back to an ancient version of Cython will prevent the libyaml extension from functioning on newer versions of Python.

Since it sounds like you have a ... special environment :), and it seems that older versions of Cython generate something that works in it, I'd suggest just pulling the source branch you want and rebuilding the dist locally with whichever version of Cython works for you, then installing from that. Since it seems that the issue is related to Cython, and it's working fine for the silent masses, your only other recourse might be to try and get the Cython folks a standalone reproduction. If Cython makes a change that fixes it, we'll use that the next time we build a dist, but otherwise, it doesn't seem like there's anything we can do. I'm going to close this for now, but if there's any movement on the Cython side that results in a patched Cython, feel free to reopen.

**Closed by nitzmahone** 2020-07-31 22:53 UTC
