### ISSUE TITLE
Using yaml.load(stream, Loader=yaml.SafeLoader) still prints deprecation warning

### ISSUE THREAD

**Issue by licht1stein** [yaml/pyyaml#340] opened 2019-09-20 09:30 UTC
Code:

![image](https://user-images.githubusercontent.com/35418634/65316311-63f9a200-dba2-11e9-9143-d72ab1fb4179.png)

Error:

![image](https://user-images.githubusercontent.com/35418634/65316348-74aa1800-dba2-11e9-89ef-e2541383ac5a.png)

**Comment by perlpunk** [comment] 2019-09-20 10:47
See https://docs.python.org/3.7/library/warnings.html
> Repetitions of a particular warning for the same source location are typically suppressed.

So you probably get the warning at some point, but only once. I think that can be configured, but is not a PyYAML issue.

If you never get the warning, then something is wrong, but then could you please create a reproducible example?

**Comment by nitzmahone** [comment] 2019-09-20 16:26
I'm also unable to reproduce this with the information given.

**Comment by perlpunk** [comment] 2019-11-18 11:37
Since we can't reproduce, I'm closing this.
Please reopen with more information if you still have this problem.

**Closed by perlpunk** 2019-11-18 11:37 UTC
