### ISSUE TITLE
Is ruamel.yaml going to get pulled into pyyaml?

### ISSUE THREAD

**Issue by abalter** [yaml/pyyaml#145] opened 2018-03-20 00:24 UTC
1. It seems as though reports of PyYaml's death have been greatly exaggerated.
   There are commits in the last 7 months, and the most recent closed issue was 12 days ago.
1. Apparently, ruamel.yaml has made some forward strides, and I don't know if pyyaml has kept up.

It seems like this would be a good idea because pyyaml has the most history and ruamel.yaml is more up-to-date (or so they say.

Status report?

**Comment by perlpunk** [comment] 2018-03-20 20:43
We actually would like to make a PyYAML release soon. I just started to try and help out here, but I don't have much experience with Python so far, so what I can do is limited.
Maybe @ingydotnet can comment on the plan.

As far as I know ruamel and PyYAML have different implementations, but that's about all I know.
If you look at http://matrix.yaml.io/ there are some differences between them, although these are mostly edge cases.
I think there are many other issues to discuss if the plan is to replace PyYAML with ruamel.

**Comment by perlpunk** [comment] 2018-03-20 20:49
Closing, as it was intended to be a comment on #46

**Closed by perlpunk** 2018-03-20 20:49 UTC
