### ISSUE TITLE
Unable to install in Python 3.12 environment

### ISSUE THREAD

**Issue by RNarayan73** [yaml/pyyaml#781] opened 2024-02-02 14:54 UTC
When installing in aa Python 3.12 environment, the following error occurs:

```
(skl312) PS C:\Users\naray\Python\venvs\skl312> pip install "pyyaml (==6.0)"

Collecting pyyaml==6.0
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 2.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\naray\Python\venvs\skl312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\naray\Python\venvs\skl312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\naray\Python\venvs\skl312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\command\sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "C:\Users\naray\AppData\Local\Temp\pip-build-env-b2jh9uqk\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
Please update the wheels for Python 3.12

Thanks,

Narayan

**Comment by nitzmahone** [comment] 2024-02-02 15:58
6.0 is not supported on 3.12- duplicate of every other issue with the same error message

**Closed by nitzmahone** 2024-02-02 15:58 UTC
