### ISSUE TITLE
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:value'

### ISSUE THREAD

**Issue by aleksandr-vin** [yaml/pyyaml#683] opened 2022-12-04 18:27 UTC
The yaml doc
```yaml
op: =
```
is not loading:
```
(venv) % pip install pyyaml
Collecting pyyaml
  Using cached PyYAML-6.0-cp310-cp310-macosx_11_0_arm64.whl (173 kB)
Installing collected packages: pyyaml
Successfully installed pyyaml-6.0
(venv) % python -c "import yaml ; yaml.load_safe('op: = ')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'yaml' has no attribute 'load_safe'. Did you mean: 'load_all'?
(venv) % python -c "import yaml ; yaml.safe_load('op: = ')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/private/tmp/venv/lib/python3.10/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:value'
  in "<unicode string>", line 1, column 5:
    op: =
        ^
```

**Comment by aleksandr-vin** [comment] 2022-12-04 18:30
I reported an issue initially on https://github.com/pre-commit/pre-commit-hooks/issues/846 but it looks like its place is here

**Comment by nitzmahone** [comment] 2022-12-07 17:11
It looks like you're running afoul of this: https://yaml.org/type/value.html. Short answer is "quote the equals if you want it to work in PyYAML", since this appears at first blush to be one of those 1.1-side-spec-isms that doesn't have an analogue in 1.2, but someone that's more of a spec expert might correct me if I'm wrong.

**Comment by aleksandr-vin** [comment] 2022-12-09 16:31
Thanks @nitzmahone.

I'm getting that yaml part in the process of converting a json data into yaml, with the pipeline like this:
```
echo '{"op":"="}' | yq -P eval
```
And the json I receive from Grafana's /api/dashboards/uid/{uid} api call. So it's not easy/tidy to quote or prefix the value.

**Comment by perlpunk** [comment] 2022-12-29 21:08
Duplicate of https://github.com/yaml/pyyaml/issues/89

**Closed** 2022-12-29 21:09 UTC
Labels: question

**Comment by nitzmahone** [comment] 2023-01-05 02:18
@perlpunk yay for dupe issue necromancy :laughing:

@aleksandr-vin If you can do things in the Python environment before the document is loaded, the following *awful hack* will let all subsequent document parses succeed in the presence of a value like that:

`del(yaml.resolver.Resolver.yaml_implicit_resolvers['='])`

Longer-term, especially since it doesn't look like that type ever really fulfilled its promise, seems like we might want to nuke it.
