### ISSUE TITLE
`yaml.dump`: "AttributeError: 'functools.partial' object has no attribute '__name__'"

### ISSUE THREAD

**Issue by allefeld** [yaml/pyyaml#541] opened 2021-07-29 21:08 UTC
Code:

```python
import pandas as pd
import numpy as np
import yaml

x = pd.DataFrame({
    'a': np.array([1.0, 2.0])
})

yaml.dump(x)
```

Result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 342, in represent_object
    return self.represent_mapping(
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 346, in represent_object
    return self.represent_sequence(tag+function_name, args)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 286, in represent_tuple
    return self.represent_sequence('tag:yaml.org,2002:python/tuple', data)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 331, in represent_object
    if function.__name__ == '__newobj__':
AttributeError: 'functools.partial' object has no attribute '__name__'
```

Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)
PyYAML 5.4.1
Pandas 1.3.1
NumPy 1.21.1

**Comment by allefeld** [comment] 2021-07-29 21:19
The problem does not occur when dumping the array only, or dumping an empty dataframe.

**Comment by nitzmahone** [comment] 2021-07-29 21:32
Ah, this is actually something we might be able to fix- any chance you could tweak the failing line to be:
`if getattr(function, '__name__', None) == '__newobj__':`
and tell me if it works? It looks like maybe a recent pandas update is doing some shenanigans in their `reduce` impl with a partial.

Also, is the expected output a `new` or an `apply`?

**Comment by nitzmahone** [comment] 2021-07-29 21:43
After some more thought- we could fix pyyaml not to bomb here by making the consultation of the callable we get back from `reduce` defensive to not having `__name__` (as I suggested above), but it still won't result in a usable result, since we have to know that name to put in the tag. Ultimately pandas is giving back an object factory from reduce that is no longer serializable by pyyaml. It may be that they need to add `functools.wraps` to get a usable `__name__` attribute, or that the new reduce impl is using a dynamic callable that's arguably breaking the underlying pickle protocol... Either way, this can't really be fixed by pyyaml on closer inspection- pandas needs to fix their reduce impl.

**Closed** 2021-07-29 21:44 UTC

**Comment by allefeld** [comment] 2021-07-29 21:45
I was just about to try your suggestion, but my environment got corrupted and I have to recreate it.

Are you going to file an issue on Pandas? Either way, this should be fixed.

**Comment by allefeld** [comment] 2021-07-29 21:50
You seem to be correct though, applying the change just led to an error somewhere else:

```
  File "/home/ca/.conda/envs/std/lib/python3.8/site-packages/yaml/representer.py", line 339, in represent_object
    function_name = '%s.%s' % (function.__module__, function.__name__)
AttributeError: 'functools.partial' object has no attribute '__module__'
```

**Comment by nitzmahone** [comment] 2021-07-29 21:52
I can't think of a proper way to fix it here, and I have no connection to or knowledge of pandas- certainly not something I've got time to mess with. It's been working forever, they Cythonized something, and now their reduce impl is broken by returning a partial for a factory method (which we have no reasonable way to serialize in the existing tag representation)- seems like it's their regression to fix. I have no idea what the partial might be doing or how deep it might go- the python `new` tag has no way to represent such a thing. Heck, I'd be surprised if pickle (and anything else) didn't barf on this too (though pickle might be able to represent a complex factory better than a yaml tag)...

**Comment by rayadastidar** [comment] 2022-09-03 09:20
Hi! I am getting the same error. Is this issue solved?
pyyaml-6.0
pandas-1.4.4
