### ISSUE TITLE
Numbers separated by colon parse unpredictably

### ISSUE THREAD

**Issue by davetapley** [yaml/pyyaml#661] opened 2022-08-20 23:27 UTC
Repro [here](https://replit.com/@davetapley/yaml-bug#main.py):

```py
import yaml
good_yaml = '''
test:
  - 123:123
'''

good = yaml.safe_load(good_yaml)

print(good)

bad_yaml = '''
test:
  - 123:12
'''

bad = yaml.safe_load(bad_yaml)

print(bad)
```

Yields:
```
{'test': ['123:123']}
{'test': [7392]}
```

**Comment by munendra-bandela-e3333** [comment] 2022-08-21 16:14
Hi @davetapley,
I am new here. I would like to look into this.
It looks like an intentional parsing logic to me [here](https://github.com/yaml/pyyaml/blob/0abad85a17ba75c0fb431feea7a6a06125341a99/lib/yaml/constructor.py#L253)

What is the desired output?

**Comment by perlpunk** [comment] 2022-08-21 17:21
duplicate of #68 #272 #371 #395 
it's correct behavior and part of YAML 1.1

**Closed** 2022-08-21 17:21 UTC

**Comment by davetapley** [comment] 2022-08-21 21:15
I thought it'd be something like that, searched for a good five minutes and didn't find any of those issues, thanks and sorry!
